[features]
seeds = false
[programs.localnet]
solana_twitter = "A6veVg75tBf31GQMXqdkJWh2goVs99gN7DruUB1Zmsb1"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/anish/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
